### ISSUE TITLE
Where is the 'setup.py' ?

### ISSUE THREAD

**Issue by ttma1046** [github-tooling/ghtopdep#10]
```
$ git clone https://github.com/github-tooling/ghtopdep
$ cd ghtopdep
$ python setup.py install
```
Where is the 'setup.py' ?

**Comment by peterjaap** [comment]
@andriyor can you shed a light on this?

**Comment by andriyor** [comment]
For developing this project I use Poetry
They generate setup.py from pyproject.toml in build time and put to sdist and wheel https://github.com/python-poetry/poetry/issues/761
So now I just added sutup.py generated by using dephell https://dephell.readthedocs.io/cmd-deps-convert.html
Can you confirm that all works properly?

**Comment by peterjaap** [comment]
Jep, works! Thanks!
