### ISSUE TITLE
Upgrade dependencies / housekeeping work

### ISSUE THREAD

**Issue by mxschmitt** [github-tooling/ghtopdep#15]
I would be open to contribute to that tool, if someone takes care about reviewing / landing the patches. I thought about the following:

- Upgrade normal dependencies to make i Python 3.9 compatible, see https://github.com/rushter/selectolax/issues/38
- Don't use https://github.com/dephell/dephell anymore
- Maybe get rid of poetry/pyproject.toml, since its 1:1 the same as setup.py? (I'm no Python expert)
- Get rid of README.rst the markdown variant should be enough
- Have the version automatically generated via setuptools
- Maybe release via GitHub Actions and have a small test?

cc @andriyor

**Comment by andriyor** [comment]
Thanks for your interest in the project and for pushing me to update selectolax
Just published a new version

> Don't use https://github.com/dephell/dephell anymore
> Maybe get rid of poetry/pyproject.toml, since its 1:1 the same as setup.py? (I'm no Python expert)

For developing purpose, build and publish a package to PyPi I use Poetry 
They generate setup.py from pyproject.toml in build time and put to sdist and wheel python-poetry/poetry#761
dephell used to generate setup.py to support editable install https://github.com/github-tooling/ghtopdep/issues/10
https://dephell.readthedocs.io/cmd-deps-convert.html#more-examples

**Comment by andriyor** [comment]
Seems like we can just replace the whole generated file with such code

`import setuptools; setuptools.setup() `

 https://github.com/python-poetry/poetry/issues/761#issuecomment-803487606 

but currently i don't know which python version supports pyproject.toml

**Comment by mxschmitt** [comment]
The installation of ghtopdep works now on Python 3.9 on Debian. 💯 

Feel free to close this issue.

**Comment by andriyor** [comment]
Since the bottleneck of this project is not parsing of html, what do you think about using other packages without C binding
