### ISSUE TITLE
Switch to asynchronous getting

### ISSUE THREAD

**Issue by nnewram** [github-tooling/ghtopdep#17]
The program runs extremely slow for repositories which have a large amount of dependents.
To resolve this, using an asynchronous library instead of normal requests would be preferred as most runtime is spent waiting for tcp.

**Comment by Dobatymo** [comment]
I think that's not possible. Because you need the current page to figure out the URL of the next one. It's not as simple as downloading `?page=1`, `?page=2` and so on in parallel. Blame Github for not providing a better interface.
