### ISSUE TITLE
Support for Python 3.10.x - Bump github3 version to 3.2.0

### ISSUE THREAD

**Issue by nickolasaperes** [github-tooling/ghtopdep#20]
Currently installing ghtopdep through PyPI will install github3.py 1.3.0 which is not compatible with Python > 3.10.
Later on I will add a PR to this.

**Comment by nickolasaperes** [comment]
#21

**Comment by andriyor** [comment]
Hi, I just published a new version of package with an updated setup.py
Thank you for pushing me to do it
Can you check it and tell does it works as expected?

**Comment by nickolasaperes** [comment]
Hi, it worked as expected! 

Thank you!
