### ISSUE TITLE
Progress bar needed

### ISSUE THREAD

**Issue by ishandutta2007** [github-tooling/ghtopdep#8]
For repos with lots of dependents it takes hell of a long time to fetch, hence please show a status what percent fetched or remaining.

**Comment by andriyor** [comment]
I agree with you that progress bar is really needed in such case
But the only problem is that there is no clear definition of how many pages the parser should scrape. Counter that shows project dependents is not accurate enough. I will give an example on https://github.com/dropbox/dropbox-sdk-js repo has 2110 dependents so scraper must process approximately 71 pages (2110 / 30) but actually only 57 pages. I can only print approximately time it takes.
If you know a better way to calculate it PR awe welcome.

Sorry for my English its not my mother tongue.

**Comment by ishandutta2007** [comment]
approximate estimation should be fine.

**Comment by abeluck** [comment]
I thought the program had hung, and came here to report it. But now I suspect it is just taking a long time. A progress bar, even approximate would be useful.
